

const handledSbgnClasses = new Set()
.add('unspecified entity')
.add('simple chemical')
.add('macromolecule')
.add('nucleic acid feature')
.add('perturbing agent')
.add('source and sink')
.add('complex')
.add('process')
.add('omitted process')
.add('uncertain process')
.add('association')
.add('dissociation')
.add('phenotype')
.add('tag')
.add('consumption')
.add('production')
.add('modulation')
.add('stimulation')
.add('catalysis')
.add('inhibition')
.add('necessary stimulation')
.add('logic arc')
.add('equivalence arc')
.add('and operator')
.add('or operator')
.add('not operator')
.add('and')
.add('or')
.add('not')
.add('nucleic acid feature multimer')
.add('macromolecule multimer')
.add('simple chemical multimer')
.add('complex multimer')
.add('compartment');

module.exports = (sbgnClass) => handledSbgnClasses.has(sbgnClass);
